---
plugin: aws_ec2
# Populate inventory with instances in these regions
regions:
  - ap-southeast-2
filters:
  tag:Project: jenkins
keyed_groups:
  - prefix: tag # prefix is 'tag_'
    key: tags['Role'] # the Role tag can be 'master' or 'node'

    # so the groups are tag_master and tag_node